### PR TITLE
fix: When pencil icon in form edit page is clicked the focus is on the form name and user can edit the form name

### LINKED ISSUE #142: Edit logo
### Is your proposal related to a problem?

Edit logo(The pen logo at right of the form name)  would be better if its more white on dark 

### Describe the solution you'd 

I think we should replace the pen logo with a more visible white logo and make it a label for the form name input so that whenever user clicks on it, the cursor will be placed inside the forms name input

### Additional context

Screenshot from 2023-10-13 12-18-18

### PR DESCRIPTION
**Pull request by Anandateertha**
## What does this PR do?

This PR basically fixes the bug that is when the pencil icon in the form edit page (beside form name) is pressed the focus is turned on on the form name and the user can edit the form name.

Fixes #142 

BEFORE

https://github.com/piyushgarg-dev/review-app/assets/131521505/a0329a9d-dc06-4167-b105-a77f47545192

AFTER

https://github.com/piyushgarg-dev/review-app/assets/131521505/360e2d60-3521-4933-acf6-020999a63bf5

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
1. Create a project.
2. Create a form.
3. Click on edit icon.
4. Now click on the pencil icon in the form edit page.

If you have an existing project and a form just click on http://app.localhost:3000/dashboard/subdomain/forms/ and click on edit icon to redirect to form edit page.

- Are there environment variables that should be set?
- No

- What are the minimal test data to have?
- Project, Form

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: components/Dashboard/FormEdit.tsx [hunk 1]
```diff
@@ -130,15 +130,23 @@ const FormEdit: React.FC<FormEditProps> = ({ reviewForm, onStepChange }) => {
...
+                    <Button
+                    type='button'
+                    style={{ backgroundColor: 'transparent' }}
+                    onClick={() => {
+                      const input = document.getElementById('nameInput');
+                      if (input) {
+                        input.focus();
+                      }
+                    }}
+                    >
```
Comment (piyushgarg-dev) [inline components/Dashboard/FormEdit.tsx:147]: Hey @Anandateertha 😄
Can we change this to `useRef`?

File: components/Dashboard/FormEdit.tsx [hunk 2]
```diff
@@ -130,15 +130,23 @@ const FormEdit: React.FC<FormEditProps> = ({ reviewForm, onStepChange }) => {
...
+                    <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11.8536 1.14645C11.6583 0.951184 11.3417 0.951184 11.1465 1.14645L3.71455 8.57836C3.62459 8.66832 3.55263 8.77461 3.50251 8.89155L2.04044 12.303C1.9599 12.491 2.00189 12.709 2.14646 12.8536C2.29103 12.9981 2.50905 13.0401 2.69697 12.9596L6.10847 11.4975C6.2254 11.4474 6.3317 11.3754 6.42166 11.2855L13.8536 3.85355C14.0488 3.65829 14.0488 3.34171 13.8536 3.14645L11.8536 1.14645ZM4.42166 9.28547L11.5 2.20711L12.7929 3.5L5.71455 10.5784L4.21924 11.2192L3.78081 10.7808L4.42166 9.28547Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
+                    </Button>
```
Comment (piyushgarg-dev) [inline components/Dashboard/FormEdit.tsx:149]: Let's use some icon here from lucide-react instead of raw SVG 😄

**Review by piyushgarg-dev — CHANGES_REQUESTED** [review]

File: components/Dashboard/FormEdit.tsx (hunk 2 above)
Comment (Anandateertha) [reply components/Dashboard/FormEdit.tsx:149]: Yeah I will the changes right now!

File: components/Dashboard/FormEdit.tsx (hunk 1 above)
Comment (Anandateertha) [reply components/Dashboard/FormEdit.tsx:147]: I am not able to use "useRef" because it is giving some kind of error saying "existing ref will be overwritten".

**Review by hemantwasthere — APPROVED** [review]
LGTM

**Comment by Anandateertha** [comment]
> LGTM

Thank you! 😊

**Comment by Anandateertha** [comment]
> > LGTM
> 
> Thank you! 😊 Can I expect it to merge?😁

**Comment by Anandateertha** [comment]
@piyushgarg-dev Can you merge this PR as it is approved?

**Comment by piyushgarg-dev** [comment]
Hey @Anandateertha 
LGTM as well, can you share a final video after making useRef change to make sure its working 
 😄

File: components/Dashboard/FormEdit.tsx [hunk 3]
```diff
@@ -123,15 +125,21 @@ const FormEdit: React.FC<FormEditProps> = ({ form, onStepChange }) => {
               <FormControl>
                 <div className="relative mt-4 w-fit">
                   <input
+                    ref={inputref}
                     disabled={form.formState.isSubmitting}
                     className="w-[7.5rem] rounded bg-transparent px-1 py-1 text-xl font-bold outline-dashed outline-1 outline-transparent duration-100 hover:outline-gray-300 focus:outline-gray-300"
-                    {...field}
```
Comment (piyushgarg-dev) [inline components/Dashboard/FormEdit.tsx:128]: Why did we removed ...field here?

Comment (Anandateertha) [reply components/Dashboard/FormEdit.tsx:128]: > Why did we removed ...field here?

Because it was throwing an error saying "'ref' is specified more than once, so this usage will be overwritten. and 
`{...field}` This spread always overwrites this property."

Comment (Anandateertha) [reply components/Dashboard/FormEdit.tsx:128]: @piyushgarg-dev This is the video showing the working of the pencil icon as you requested.

https://github.com/piyushgarg-dev/review-app/assets/131521505/8be532a0-cb13-4214-991f-964d4e286cf7

Comment (hemantwasthere) [inline components/Dashboard/FormEdit.tsx:128]: add this `{...field}` before `ref={inputRef}` then it will not show that double initialization error

Comment (hemantwasthere) [reply components/Dashboard/FormEdit.tsx:128]:
```
<input
                    {...field}
                    disabled={form.formState.isSubmitting}
                    className="w-[7.5rem] rounded bg-transparent px-1 py-1 text-xl font-bold outline-dashed outline-1 outline-transparent duration-100 hover:outline-gray-300 focus:outline-gray-300"
                    ref={inputref}

```                    
like this

**Review by hemantwasthere — CHANGES_REQUESTED** [review]

File: components/Dashboard/FormEdit.tsx (hunk 3 above)
Comment (Anandateertha) [reply components/Dashboard/FormEdit.tsx:128]: Changes done as you have requested and I have commited the changes.

**Review by hemantwasthere — APPROVED** [review]
Looks nice! Thanks for contributing 💙
