### PR TITLE
fix: landing page hero section button alignment fixed

### LINKED ISSUE #254: [Bug]: Text overlapping with Button on Landing Page in Mozilla Firefox
### Describe the bug

The button is overlapping with text in the hero section of Landing Page

### To Reproduce

1. Go to Landing Page - localhost:3000 (Open on Mozilla Firefox)
2. Check the Hero Section

### Expected behavior

The button and the the text should not overlap 

### Screenshots/Videos

image

### Additional context

_No response_

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

### PR DESCRIPTION
**Pull request by tanpreetjolly**
## What does this PR do?

It fixes the alignment of landing page button which was overlapping with the text.  

Fixes #254 
I have used a flex container for the parent container to fix the alignment and layout of the hero section so that the hero button is no longer overlapping
Before :

Screenshot from 2023-10-22 13-25-07

After : 

Screenshot from 2023-10-22 13-32-19

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How should this be tested?

- Go to the Landing Page
- Check the Hero Section
- Check the alignment "Get Started for Free" button in the Hero Section

### CODE REVIEW

**Comment by tanpreetjolly** [comment]
#254

File: pages/templates/ebraj/index.tsx [hunk 1]
```diff
@@ -161,7 +161,7 @@ export const HeroSection = () => {
         <div className="h-60 bg-gradient-to-br from-violet-500 to-violet-600 blur-[200px] dark:from-sky-900 dark:to-sky-950"></div>
         <div className="h-60 bg-gradient-to-r from-violet-500 to-violet-600 blur-[200px] dark:from-sky-800 dark:to-sky-900"></div>
       </div>
-      <main className="text-center">
+      <main className="text-center flex flex-col">
```
Comment (sohan9819) [inline pages/templates/ebraj/index.tsx:164]: If you had added `justify-center items-center` here , it would have achieved the same result without the need to make changes to the button. Nevertheless, I believe the output remains consistent in both scenarios👍.

**Comment by sohan9819** [comment]
LGTM 👍

**Comment by tanpreetjolly** [comment]
Yeah I think you are right, that would achieve the same result without touching the button.

File: pages/templates/ebraj/index.tsx (hunk 1 above)
Comment (hemantwasthere) [reply pages/templates/ebraj/index.tsx:164]: @tanpreetjolly Can you please do this changes instead of current change you have done.

**Review by hemantwasthere — CHANGES_REQUESTED** [review]

**Comment by tanpreetjolly** [comment]
All right I will do that

**Comment by tanpreetjolly** [comment]
@hemantwasthere  I have done the changes you requested please check

**Review by hemantwasthere — APPROVED** [review]
LGTM!
